DELIMITER = '_'

MAIN_BRANCH_NAME = 'main'

BRANCH_NAME_PATTERN = 'ab#[0-9]+'

WORK_ITEM_NUMBER_PATTERN = '\A[0-9]+\Z'

COMPLETE_BRACH_PATTERN = 'ab#[0-9]+{}ab#[0-9]+'.format(DELIMITER)

GET_CURRENT_BRANCH_CMD = 'git branch --show-current'

CREATE_NEW_STORY_BRANCH_CMD = 'git checkout -b {}'

STORY_OPERAND = 'story'

TASK_OPERAND = 'task'

START_OPERATION = 'start'

COMPLETE_OPERATION = 'complete'

ALLOWED_OPERATIONS = [START_OPERATION, COMPLETE_OPERATION]

ALLOWED_OPERANDS = [STORY_OPERAND, TASK_OPERAND]

OPERATIONS_REQUIRE_WORK_ITEM = [START_OPERATION]
