DELIMITER = '_'

SPACE_CHAR_REPLACEMENT = '%SPACE%'

MAIN_BRANCH_NAME = 'main'

WORK_ITEM_NUMBER_CHARS = '[0-9]'

WORK_ITEM_NUMBER_PATTERN = '\A{}+\Z'.format(WORK_ITEM_NUMBER_CHARS)

COMPLETE_STORY_BRACH_PATTERN = '\A{0}+{1}{0}+\Z'.format(WORK_ITEM_NUMBER_CHARS, DELIMITER)

IS_TASK_BRANCH_PATTERN = '\A{0}+_{0}+\Z'.format(WORK_ITEM_NUMBER_CHARS)

IS_STORY_BRANCH_PATTERN = '\A{0}+_{0}+\Z|{1}'.format(WORK_ITEM_NUMBER_CHARS, WORK_ITEM_NUMBER_PATTERN)

GET_STORY_NUMBER_PATTERN = '\A[0-9]+'

GET_TASK_NUMBER_PATTERN = '[0-9]+\Z'

GET_CURRENT_BRANCH_CMD = 'git branch --show-current'

FETCH_ALL_CMD = 'git fetch --all'

CREATE_NEW_STORY_BRANCH_CMD = 'git checkout -b {}'

PUSH_CURRENT_CHANGES_CMD = 'git push -u origin HEAD'

CREATE_PULL_REQUEST_CMD = 'gh pr create -w -t {} -B {}'
