DELIMITER = '_'

MAIN_BRANCH_NAME = 'main'

WORK_ITEM_NUMBER_CHARS = '[0-9]'

WORK_ITEM_NUMBER_PATTERN = '\A{}+\Z'.format(WORK_ITEM_NUMBER_CHARS)

COMPLETE_STORY_BRACH_PATTERN = '\A{0}+{1}{0}+\Z'.format(WORK_ITEM_NUMBER_CHARS, DELIMITER)

GET_CURRENT_BRANCH_CMD = 'git branch --show-current'

FETCH_ALL_CMD = 'git fetch --all'

CREATE_NEW_STORY_BRANCH_CMD = 'git checkout -b {}'

CREATE_PULL_REQUEST_CMD = ''
