#!/usr/bin/python3
import sys

from helpers import get_current_branch_name, is_main_branch, is_valid_devops_work_item_number, create_new_story_branch

provided_work_item_number = sys.argv[-1]

if not is_valid_devops_work_item_number(provided_work_item_number):
  raise Exception('You provided invalid work item number')

current_branch_name = get_current_branch_name()

if not is_main_branch(current_branch_name):
  raise Exception('Please switch to main branch before starting working on a new story')

create_new_story_branch(provided_work_item_number)
