#!/usr/bin/python3

import sys

from helpers import exit_with_failure, get_current_branch_name, unpack_list
from constants import ALLOWED_OPERANDS, ALLOWED_OPERATIONS, COMPLETE_OPERATION, START_OPERATION, STORY_OPERAND, TASK_OPERAND

from story import Story
from task import Task


argument_list = sys.argv[1:]

operand, operation, work_item_number = unpack_list(argument_list, 3)

if operand not in ALLOWED_OPERANDS:
    exit_with_failure('Operand should be one of: %s' % ', '.join(ALLOWED_OPERANDS))

if operation not in ALLOWED_OPERATIONS:
    exit_with_failure('Operand should be one of: %s' % ', '.join(ALLOWED_OPERATIONS))

if operation == START_OPERATION and not work_item_number:
  exit_with_failure('{} operation requires a DevOps work item number.'.format(operation.upper()))

current_branch_name = get_current_branch_name()


if operand == STORY_OPERAND:
  story = Story(current_branch_name)

  if operation == START_OPERATION:
    story.start(work_item_number)

  if operation == COMPLETE_OPERATION:
    story.finish()


if operand == TASK_OPERAND:
  task = Task(current_branch_name)

  if operation == START_OPERATION:
    task.start(work_item_number)

  if operation == COMPLETE_OPERATION:
    task.finish()

