#!/usr/bin/python3


from helpers import create_task_pr, fetch_remote_changes, get_current_branch_name, get_story_number_from_branch_name, get_task_number_from_branch_name, is_story_branch, is_task_branch, push_local_changes


current_branch_name = get_current_branch_name()

if not is_story_branch(current_branch_name):
  raise Exception('Your current branch doesn\'t seem to be related to a story')

if not is_task_branch(current_branch_name):
  raise Exception('Your current branch doesn\'t seem to be a task branch')

story_number = get_story_number_from_branch_name(current_branch_name)

task_number = get_task_number_from_branch_name(current_branch_name)

fetch_remote_changes()
push_local_changes()

create_task_pr(story_number, task_number)