#!/usr/bin/python3

import sys

from helpers import get_current_branch_name, unpack_list
from constants import ALLOWED_OPERANDS, ALLOWED_OPERATIONS, START_OPERATION

from git_devops_story_start import start_story
from git_devops_story_finish import finish_story
from git_devops_task_start import start_task
from git_devops_task_finish import finish_task

argument_list = sys.argv[1:]

operand, operation, work_item_number = unpack_list(argument_list, 3)

if operand not in ALLOWED_OPERANDS:
    raise Exception('Operand should be one of: %s', ', '.join(ALLOWED_OPERANDS))

if operation not in ALLOWED_OPERATIONS:
    raise Exception('Operand should be one of: %s', ', '.join(ALLOWED_OPERATIONS))

if operation == START_OPERATION and not work_item_number:
  raise Exception('{} operation requires a DevOps work item number.'.format(operation.upper()))

current_branch = get_current_branch_name()


if operand == STORY_OPERAND:
  pass